services:
  # PostgreSQL database
  postgres:
    image: postgres:15
    container_name: admin-notes-postgres
    environment:
      POSTGRES_DB: admin_notes_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./drizzle:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Admin Notes AI POC Service
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: admin-notes-ai-app
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgresql://postgres:password@postgres:5432/admin_notes_ai
  #     - CLAUDE_API_KEY=${CLAUDE_API_KEY}
  #     - PORT=3000
  #     - HOST=0.0.0.0
  #     - LOG_LEVEL=info
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   restart: unless-stopped
  #   volumes:
  #     - .:/app
  #     - /app/node_modules

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: admin-notes-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    profiles:
      - admin

volumes:
  postgres_data: