# Spring Boot Configuration for Java 21
# Updated for Spring Boot 3.3.3
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-stacktrace: on_param

spring:
  application:
    name: flo-summarizer

  # Database Configuration (H2 for development)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # Jackson Configuration for Java 21
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    env:
      enabled: true

# Logging Configuration
logging:
  level:
    com.flo.summarizer: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Java 21 specific configurations
java:
  version: 21
  features:
    string-templates: true
    pattern-matching: true
    records: true